import { test, expect } from '@playwright/test'

test('test', async ({ page }) => {
    await page.goto('http://localhost:3000/')
    await page.getByRole('textbox', { name: 'Логин' }).click()
    await page.getByRole('textbox', { name: 'Логин' }).fill('1')
    await page.getByRole('textbox', { name: 'Пароль' }).click()
    await page.getByRole('textbox', { name: 'Пароль' }).fill('1')
    await page.getByRole('button', { name: 'Отправить' }).click()
    
    await page.locator(':nth-match(:text("В корзину"), 3)').click()
    await page.locator(':nth-match(:text("В корзину"), 3)').click()
    await page.locator(':nth-match(:text("В корзину"), 3)').click()
    await page.locator(':nth-match(:text("В корзину"), 2)').click()
    await page.locator(':nth-match(:text("В корзину"), 2)').click()
    
    await page.getByRole('img', { name: 'корзина товаров' }).click()
    await page.locator('label').click()
    await page.getByRole('button', { name: 'Оформить заказ' }).click()
    await page.getByRole('textbox', { name: 'Введите ваше ФИО' }).click()
    await page.getByRole('textbox', { name: 'Введите ваше ФИО' }).fill('ИвановИван ')
    await page.getByRole('textbox', { name: 'Введите ваше ФИО' }).press('ArrowLeft')
    await page.getByRole('textbox', { name: 'Введите ваше ФИО' }).press('ArrowLeft')
    await page.getByRole('textbox', { name: 'Введите ваше ФИО' }).press('ArrowLeft')
    await page.getByRole('textbox', { name: 'Введите ваше ФИО' }).press('ArrowLeft')
    await page.getByRole('textbox', { name: 'Введите ваше ФИО' }).fill('Иванов Иван')
    await page.getByRole('textbox', { name: 'Введите ваше ФИО' }).press('ArrowRight')
    await page.getByRole('textbox', { name: 'Введите ваше ФИО' }).press('ArrowRight')
    await page.getByRole('textbox', { name: 'Введите ваше ФИО' }).press('ArrowRight')
    await page.getByRole('textbox', { name: 'Введите ваше ФИО' }).press('ArrowRight')
    await page.getByRole('textbox', { name: 'Введите ваше ФИО' }).fill('Иванов ИванИванович')
    await page.getByRole('textbox', { name: 'Введите ваше ФИО' }).press('ArrowLeft')
    await page.getByRole('textbox', { name: 'Введите ваше ФИО' }).press('ArrowLeft')
    await page.getByRole('textbox', { name: 'Введите ваше ФИО' }).press('ArrowLeft')
    await page.getByRole('textbox', { name: 'Введите ваше ФИО' }).press('ArrowLeft')
    await page.getByRole('textbox', { name: 'Введите ваше ФИО' }).press('ArrowLeft')
    await page.getByRole('textbox', { name: 'Введите ваше ФИО' }).press('ArrowLeft')
    await page.getByRole('textbox', { name: 'Введите ваше ФИО' }).press('ArrowLeft')
    await page.getByRole('textbox', { name: 'Введите ваше ФИО' }).press('ArrowLeft')
    await page.getByRole('textbox', { name: 'Введите ваше ФИО' }).fill('Иванов Иван Иванович')
    await page.getByRole('textbox', { name: 'Дата рождения' }).fill('1993-06-09')
    await page.getByRole('textbox', { name: 'Электронная почта' }).click()
    await page.getByRole('textbox', { name: 'Электронная почта' }).fill('something@esomemail.com')
    await page.getByRole('textbox', { name: 'Электронная почта' }).press('ControlOrMeta+a')
    await page.getByRole('textbox', { name: 'Электронная почта' }).fill('some@email.com')
    await page.getByRole('textbox', { name: 'Город' }).click()
    await page.getByRole('textbox', { name: 'Город' }).fill('Москва')
    await page.getByRole('textbox', { name: 'Улица' }).click()
    await page.getByRole('textbox', { name: 'Улица' }).fill('Арбат')
    await page.getByRole('textbox', { name: 'Номер дома' }).click()
    await page.getByRole('textbox', { name: 'Номер дома' }).fill('3')
    await page.getByRole('textbox', { name: 'Номер карты' }).click()
    await page.getByRole('textbox', { name: 'Номер карты' }).fill('11111111111')
    await page.getByRole('textbox', { name: 'Карта действительна до' }).click()
    await page.getByRole('textbox', { name: 'Карта действительна до' }).fill('02.29')
    await page.locator('form div').filter({ hasText: 'Соглашение об обработке персональных данных' }).click()
    await page.getByRole('button', { name: 'Отправить' }).click()
    await page.locator('path').click()
    await page.getByRole('button', { name: 'Очистить корзину' }).click()
})
